services:
  violet-mysql:
    platform: linux/x86_64
    image: mysql
    container_name: violet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./config/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306

  violet-redis:
    image: redis
    container_name: violet-redis
    command:
      - redis-server --port 6379
      - redis-cli config set notify-keyspace-events AKE
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
